<h1 align="center">NumPy Assignment</h1>

<p align="center">
<b>Submitted by:</b> Kala Sravani<br>
<b>Batch:</b> 2
</p>

In [3]:
import numpy as np

# Section A – Conceptual Understanding

A1. Why are NumPy arrays generally preferred over plain Python lists for numerical computation in AI/ML workloads?

Answer:

NumPy arrays are better for numerical calculations because they are faster and use memory efficiently. They also support vectorized operations, so we can perform calculations on many values at once without writing loops. This makes NumPy useful for AI/ML tasks.

A2. Explain vectorization. Why does replacing an explicit Python loop with a vectorized NumPy operation matter with large datasets?

Answer:

Vectorization means performing an operation on an entire NumPy array at once instead of using a loop. It makes the code shorter and usually faster, especially when working with large amounts of data.

A3. For compatible 2D arrays A and B, explain the difference between A * B and A @ B. Give one neural-network situation where each is useful.

Answer:

A * B performs element-wise multiplication, so corresponding values are multiplied. A @ B performs matrix multiplication. In neural networks, * can be used for element-wise scaling or masking, while @ is commonly used to multiply inputs with weights.

A4. What is broadcasting in NumPy? State the general compatibility rule for broadcasting.

Answer:

Broadcasting allows NumPy to perform operations on arrays with different shapes. NumPy compares the dimensions from the last one, and the dimensions must either be equal or one of them must be 1.

A5. What is the difference between flatten() and ravel()? Which would you prefer for a large image when memory is constrained, and why?

Answer:

Both flatten() and ravel() convert an array into a 1D array. flatten() creates a copy, while ravel() may return a view and therefore use less memory. For a large image with limited memory, I would prefer ravel() when possible.

A6. Explain the difference between axis=0 and axis=1 in aggregation functions. Give a small example.

Answer:

In a 2D array, axis=0 performs the calculation down the rows, giving a result for each column. Axis=1 performs the calculation across the columns, giving a result for each row.

In [5]:
#EXAMPLE:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

[5 7 9]
[ 6 15]


A7. What is the purpose of scaling features before applying ML algorithms? Contrast normalization vs standardization.

Answer:

Scaling features helps bring different numerical features to comparable ranges. Normalization usually changes values to a fixed range such as 0 to 1, while standardization changes values using the mean and standard deviation.

A8. What is np.nanmean() used for? What does np.mean() do when the data contains NaN?

Answer:

np.nanmean() calculates the mean while ignoring NaN values. np.mean() normally returns NaN if the data contains a NaN value.

A9. Suppose X has shape (samples, features). For a batch of RGB images, what exact shape would represent 64 images of size 128×128?

Answer:

For RGB images, the shape is represented as (number of images, height, width, channels). Therefore, 64 RGB images of size 128×128 would have the shape (64, 128, 128, 3).

A10. Why is reproducibility important in ML experiments? How does np.random.default_rng(seed) help?

Answer:

Reproducibility helps us get the same random results when we repeat an experiment. Using np.random.default_rng() with a fixed seed makes random number generation repeatable. This makes testing and comparing results easier.

## Section B – Predict the Output

B1. Predict the exact output and/or resulting shape. Justify in one sentence.
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print((a + b).shape)




a = np.array([1, 2, 3])

b = np.array([[1], [2], [3]])

print((a + b).shape)

Predicted output:

(3, 3)

B2. Predict the output and/or shape.
x = np.arange(1, 7).reshape(2, 3)
print(x[:, 1])



x = np.arange(1, 7).reshape(2, 3)

print(x[:, 1])

Predicted output:

[2 5]

B3. Predict the output and/or shape. 
arr = np.array([5, 10, 15, 20, 25])
print(arr[arr % 10 == 0])





arr = np.array([5, 10, 15, 20, 25])

print(arr[arr % 10 == 0])

Predicted output:

[10  20]

B4. Predict the output and/or shape.
m = np.array([[1, 2], [3, 4]])
print(m.T @ m)


m = np.array([[1, 2],
              [3, 4]])

print(m.T @ m)

Predicted output:

[[10 14]
 [14 20]]

B5. Predict the output and/or shape. 
data = np.array([1, 2, np.nan, 4])
print(np.mean(data), np.nanmean(data))


data = np.array([1, 2, np.nan, 4])

print(np.mean(data), np.nanmean(data))

Predicted output:

nan 2.3333333333333335

B6. Predict the output and/or shape. 
x = np.array([10, 20, 30])
y = np.where(x > 15, 1, 0)
print(y)


x = np.array([10, 20, 30])

print(np.where(x > 15, 1, 0))

Predicted output:

[0 1 1]

B7. Predict the output and/or shape.
a = np.zeros((3, 4))
print(a.ndim, a.size)


z = np.zeros((3, 4))

print(z.ndim, z.size)

Predicted output:

2 12

B8. Predict the output and/or shape.
arr = np.arange(1, 13).reshape(3, 4)
print(arr[::-1, ::-1])


x = np.arange(1, 13).reshape(3, 4)

print(x[::-1, ::-1])

Predicted output:

[[12 11 10  9]

 [ 8  7  6  5]
 
 [ 4  3  2  1]]

## Section C – Vectorized Coding Tasks

C1. Given a 1D NumPy array of exam scores, use np.where() to produce labels 'P' (score >= 40) or 'F' (score < 40). 

In [9]:
import numpy as np

scores = np.array([35, 40, 55, 28, 75])

labels = np.where(scores >= 40, "P", "F")

print(labels)

['F' 'P' 'P' 'F' 'P']


Explanation: np.where() applies the pass/fail condition to all scores without using a loop

C2. Write a function standardize(x) that takes a 1D NumPy array and returns its z-score standardized version using only NumPy.

In [12]:
def standardize(x):
    return (x - np.mean(x)) / np.std(x)

x = np.array([1, 2, 3, 4, 5])

print(standardize(x))

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


Explanation: The function subtracts the mean and divides by the standard deviation to standardize the values.

C3. Combine two 2D arrays (batches) with the same number of features using the appropriate stacking method. Print the shape of the combined array.


In [14]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[7, 8, 9],
              [10, 11, 12]])

combined = np.vstack((a, b))

print(combined)
print(combined.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


Explanation: np.vstack() combines the two batches row-wise because both arrays have the same number of features.

C4. Given X with shape (100, 5), compute the column-wise mean and standard deviation, then standardize X using a single vectorized expression.


In [17]:
X = np.random.default_rng(42).normal(size=(100, 5))

mean = X.mean(axis=0)
std = X.std(axis=0)

X_standardized = (X - mean) / std

print("Mean:", mean)
print("Standard deviation:", std)
print("Standardized shape:", X_standardized.shape)

Mean: [-0.02976502 -0.0243285   0.02132587  0.00977781 -0.04264091]
Standard deviation: [0.93907585 0.86849238 0.94883911 1.05055432 0.97727443]
Standardized shape: (100, 5)


Explanation: axis=0 calculates the mean and standard deviation for each feature column, and broadcasting applies them to all rows.


C5. Given X, weights w, bias b, and true values y_true, compute the predictions using y_pred = X @ w + b and then calculate the Mean Squared Error (MSE).



In [18]:
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

w = np.array([0.5, 1.0])
b = 2

y_true = np.array([4, 6, 8])

y_pred = X @ w + b
mse = np.mean((y_true - y_pred) ** 2)

print("Predictions:", y_pred)
print("MSE:", mse)

Predictions: [4.5 6.  7.5]
MSE: 0.16666666666666666


Explanation: Matrix multiplication calculates the predictions, and MSE measures the average squared difference between predicted and true values.

C6. Using np.random.default_rng() with a fixed seed, generate 10 samples with 3 features from a normal distribution. Print the shape and confirm that using the same seed gives identical results.



In [19]:
rng1 = np.random.default_rng(42)
X1 = rng1.normal(size=(10, 3))

rng2 = np.random.default_rng(42)
X2 = rng2.normal(size=(10, 3))

print("Shape:", X1.shape)
print("Same values:", np.array_equal(X1, X2))

Shape: (10, 3)
Same values: True


Explanation: Using the same seed produces the same random values, which makes the experiment reproducible.

C7. Given a grayscale image array with pixel values in [0, 255], normalize it to [0, 1] using min-max normalization.



In [20]:
image = np.array([[0, 64, 128],
                  [192, 224, 255]])

normalized = (image - image.min()) / (image.max() - image.min())

print(normalized)

[[0.         0.25098039 0.50196078]
 [0.75294118 0.87843137 1.        ]]


Explanation: Min-max normalization converts the pixel values from their original range to the range 0 to 1.

C8. Given 4 RGB images with shape (4, 28, 28, 3), compute the average pixel value for each image across height, width, and channels. State the axis used and explain why.



In [21]:
images = np.random.default_rng(42).random((4, 28, 28, 3))

average = images.mean(axis=(1, 2, 3))

print("Shape:", average.shape)
print("Average pixel values:", average)

Shape: (4,)
Average pixel values: [0.49879444 0.49546077 0.48993754 0.50644914]


Explanation: axis=(1, 2, 3) averages across height, width, and RGB channels, leaving one average value for each of the 4 images.

## Section D – Applied / Debugging Tasks

D1. Given a raw 1D or 2D NumPy array containing NaN values, write a step-by-step process to:
1. Detect missing values.
2. Handle them appropriately and justify your choice.
3. Normalize or standardize the resulting data.
4. Implement the full pipeline on a sample array containing NaN.


In [22]:
import numpy as np

data = np.array([[10, 20, np.nan],
                 [30, np.nan, 50],
                 [40, 60, 70]])

# 1. Detect missing values
print("Missing values:")
print(np.isnan(data))

# 2. Replace NaN values with column means
column_means = np.nanmean(data, axis=0)
rows, cols = np.where(np.isnan(data))
data[rows, cols] = column_means[cols]

# 3. Standardize the data
mean = data.mean(axis=0)
std = data.std(axis=0)
standardized = (data - mean) / std

# 4. Display the result
print("Data after handling NaN:")
print(data)

print("Standardized data:")
print(standardized)

Missing values:
[[False False  True]
 [False  True False]
 [False False False]]
Data after handling NaN:
[[10. 20. 60.]
 [30. 40. 50.]
 [40. 60. 70.]]
Standardized data:
[[-1.33630621 -1.22474487  0.        ]
 [ 0.26726124  0.         -1.22474487]
 [ 1.06904497  1.22474487  1.22474487]]


Explanation:

First, np.isnan() detects the missing values. The NaN values are replaced with their respective column means so that the available data is retained. Finally, the data is standardized using the column-wise mean and standard deviation.

D2. Image Batch Understanding [8 marks]

1.Explain, with correct NumPy shapes, how a single RGB image differs from a batch of RGB images.

2.Write code to create a dummy batch of 16 images of size 64 × 64 using random pixel values.

3.Compute the average image of the batch, meaning the element-wise mean across all 16 images.

4.State the shape of your result and explain why.




1. Single RGB Image:

A single RGB image has the shape (64, 64, 3). The three channels represent Red, Green, and Blue.

2. Batch of RGB Images:

A batch of 16 RGB images has the shape (16, 64, 64, 3). The first dimension represents the number of images.

3. Average Image:

The average image is calculated across the 16 images using axis=0.

4. Shape of Average Image:

The average image has the shape (64, 64, 3) because the image dimension and RGB channels are retained while the 16-image dimension is averaged.

In [23]:
import numpy as np

# Create a batch of 16 RGB images
images = np.random.default_rng(42).random((16, 64, 64, 3))

# Compute the average image across the 16 images
average_image = np.mean(images, axis=0)

print("Batch shape:", images.shape)
print("Average image shape:", average_image.shape)

Batch shape: (16, 64, 64, 3)
Average image shape: (64, 64, 3)


Explanation:

A single RGB image has shape (64, 64, 3), while a batch has an extra dimension for the number of images: (16, 64, 64, 3). Using axis=0 averages the 16 images while keeping the height, width, and RGB channels.

D3. Debug the following code. Identify every bug, explain the shape issue and operator precedence issue, and provide the corrected code.

X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

w = np.array([0.5, 1.0, 0.2])
b = 2

y_pred = X @ w + b

y_true = np.array([10, 20, 30])

mse = np.mean(y_true - y_pred**2)

Explanation:

There are two main bugs. First, X has shape (3, 2), so W must have 2 values, but the given W has 3 values. Second, the MSE formula needs the difference to be squared before taking the mean. The corrected expression is np.mean((y_true - y_pred) ** 2).

In [24]:
import numpy as np

X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

w = np.array([0.5, 1.0])
b = 2

y_true = np.array([10, 20, 30])

y_pred = X @ w + b

mse = np.mean((y_true - y_pred) ** 2)

print("Predictions:", y_pred)
print("MSE:", mse)

Predictions: [4.5 6.  7.5]
MSE: 244.16666666666666


## Section E -Bonus

E1. Perform per-column min-max normalization on a 2D NumPy array. The solution must be fully vectorized and use no loops.



In [25]:
import numpy as np

X = np.array([[10, 20, 30],
              [20, 40, 50],
              [30, 60, 70]], dtype=float)

X_min = X.min(axis=0)
X_max = X.max(axis=0)

X_normalized = (X - X_min) / (X_max - X_min)

print(X_normalized)

[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


Explanation: axis=0 finds the minimum and maximum of each column, and broadcasting applies min-max normalization without using loops.

E2. Use a single vectorized expression with nested or combined np.where() to classify scores as:
Fail if < 40,
Average if 40–70 inclusive,
Excellent if > 70.



In [26]:
scores = np.array([25, 40, 55, 70, 85])

result = np.where(scores < 40, "Fail",
                  np.where(scores <= 70, "Average", "Excellent"))

print(result)

['Fail' 'Average' 'Average' 'Average' 'Excellent']


Explanation: Nested np.where() applies all three conditions in one vectorized expression without using loops.